### ISSUE TITLE
No heartbeat between the server side and the client side

### ISSUE THREAD

**Issue by zhenchuan9r** [simonalong/Butterfly#11]
I tried to review the interaction between the server side and the client side. It seems there is not a heartbeat mechanism so that the system relies on the hostid upward counting to avoid uuid duplication. I feel that this project is not fully completed.

看了以下服务端和客户端的交互代码，看上去客户端和服务器之间没有心跳，只能依靠hostid+1来避免重复发号，感觉这一块并没有完全做完。

**Comment by SimonAlong** [comment]
db模式下是有心跳的；zk模式下用的持久节点（其中包含过期时间）无需心跳；distribut模式下，每次用完了会向服务端请求新的分配。
