### ISSUE TITLE
低并发情况下生成出的id都是偶数 影响分库分表的公平性 能否优化

### ISSUE THREAD

**Issue by ToadKingJiang** [SimonAlong/Butterfly#3]
作者您好，低并发情况下生成出的id都是偶数 影响分库分表的公平性 ，做个问题能否优化

**Comment by SimonAlong** [comment]
你好，确实存在这个问题，这边准备把seq中的9bit进行高位和低位拆分，将低位放到低的1个bit，这样可以作为奇数偶数交替了
