### ISSUE TITLE
自增性问题

### ISSUE THREAD

**Issue by 52123333** [SimonAlong/Butterfly#4]
部分节点重启后，新启动的节点时间戳比较大，生成的id也比较大，破坏了整体的自增性？

**Comment by SimonAlong** [comment]
先说明下结论，这个没有破坏整体自增性。
原因：雪花算法中，时间字段位于高位，这边解决雪花回拨问题采用时间，是应用启动的那个时间戳，再之后就不再发生变化（只有低位的增满之后才会进位）。目前序列位分配了9bit，对应普通雪花qps为51.2w/s，一般机器都是低于这个，因此时间位对应的时间，较真实时间是慢的。下次启动，采用新的时间，就自然会很大的了。

**Comment by liucaijin** [comment]
某个节点重启之后，生成的id肯定会更大啊。部分节点的id永远更大的话是影响主键插入的性能的

**Comment by liucaijin** [comment]
就算没有重启，节点请求的量不均衡，慢慢的不同节点间同一个时刻的id的值差别也会很大

**Comment by SimonAlong** [comment]
这个改造的算法，并不保证完全的自增，只是保证局部的自增。
