### ISSUE TITLE
restful方式报错

### ISSUE THREAD

**Issue by xiaomin521309** [SimonAlong/Butterfly#6]
Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

Caued by: java.sql.SQLException: No suitable driver

正常走DB模式是无问题

**Comment by SimonAlong** [comment]
问题已经确认，后续会在1.0.3版本修复
--------------------------------------------
原因：Orm底层框架新版本将数据库驱动强依赖修改为业务依赖了，使用方要自己引入数据驱动包
